[application]
name = "showel"
default_platform = "desktop"
out_dir = "dist"
sub_package = "app"

[web.app]
title = "Showel"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[bundle]
identifier = "dev.showel.app"
publisher = "Showel"
category = "DeveloperTool"
short_description = "Fast native desktop database client built with Rust and Dioxus."
long_description = """
Showel is a lightweight native desktop database client for SQLite, PostgreSQL, and ClickHouse.
"""
resources = []

[bundle.windows]
digest_algorithm = "sha-256"

[bundle.windows.webview_install_mode.OfflineInstaller]
silent = true
